biodiversity/forum/urls.py
from django.conf.urls.defaults import *
from forum.views import *
from os import path as os_path
from django.conf import settings


urlpatterns = patterns('forum.views',
    (r'^$', 'index'),
    (r'^(?P<slug>[-\w]+)/$', 'forum_list'),
    (r'^(?P<slug>[-\w]+)/(?P<t_slug>[-\w]+)/$', 'forum_detail'),
    (r'^(?P<slug>[-\w]+)/post/new/$', 'new_topic'),
    (r'^(?P<slug>[-\w]+)/(?P<t_slug>[-\w]+)/responder/$', 'topic_reply'),
)

biodiversity/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
import settings
from os import path as os_path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^biodiversity/', include('biodiversity.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^accounts/login/$', 'django.contrib.auth.views.login', name='account_login'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'diversity.views.logout_page'),
    (r'^$', 'diversity.views.index'),
    (r'^admin/', include(admin.site.urls)),
    (r'^eventos/', include('eventos.urls')),
    (r'^bioversity/', include('diversity.urls')),
    (r'^clima/', include('clima.urls')),
    (r'^precio/', include('precio.urls')),
    (r'^documentos/', include('documentos.urls')),
    (r'^noticias/', include('noticias.urls')),
    #(r'^foro/', include('forum.urls')),
    (r'^busqueda/', include('haystack.urls')),
    (r'^tagging_autocomplete/', include('tagging_autocomplete.urls')),
    (r'^foro/', include('askbotmini.urls')),
    (r'^ayuda/$', direct_to_template, {'template': 'ayuda.html'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^files/(.*)$', 'django.views.static.serve',
                             {'document_root': os_path.join(settings.MEDIA_ROOT)}),
                           )

biodiversity/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

import datetime

class Categories(models.Model):
    titulo = models.CharField(max_length=100)

    def __unicode__(self):
        return u'%s' % self.titulo

    class Meta:
        verbose_name = 'Categorias'
        verbose_name_plural = 'Categorias'


class Forum(models.Model):
    category = models.ForeignKey(Categories)
    titulo = models.CharField(max_length=100)
    slug = models.CharField(unique=True, max_length=100, editable=False)
    descripcion = models.TextField()
    threads = models.IntegerField(default=0, editable=False)
    posts = models.IntegerField(default=0, editable=False)

    def _get_forum_latest_post(self):
        """Obtiene el ultimo post para este foro"""
        if not hasattr(self, '__forum_latest_post'):
            try:
                self.__forum_latest_post = Post.objects.filter(forum__pk=self.id).latest('time')
            except Post.DoesNotExist:
                try:
                    self.__forum_latest_post = Thread.objects.filter(forum__pk=self.id).latest('time')
                except Thread.DoesNotExist:
                    self.__forum_latest_post = None

        return self.__forum_latest_post
    forum_latest_post = property(_get_forum_latest_post)

    def save(self, force_insert=False, force_update=False):
        if self.id:
            pass
        else:
            n = Forum.objects.all().count()
            self.slug = str(n+1) + '-'  + slugify(self.titulo)
	super(Forum, self).save(force_insert, force_update)


    def __unicode__(self):
        return u'%s' % self.titulo

    class Meta:
        verbose_name = 'Foro'
        verbose_name_plural = 'Foros'

class Thread(models.Model):
    forum = models.ForeignKey(Forum)
    titulo = models.CharField(max_length=100, verbose_name='Titulo')
    author = models.ForeignKey(User)
    posts = models.IntegerField(default=0, verbose_name='Posts', editable=False)
    visto = models.IntegerField(default=0, verbose_name='Visto')
    slug = models.CharField(unique=True, max_length=100, editable=False)
    time = models.DateTimeField(blank=True, null=True)
    latest_post_time = models.DateTimeField(blank=True, null=True, verbose_name='Latest Post Time')
    body = models.TextField(verbose_name='Contenido')

    def _get_thread_latest_post(self):
        """Obtiene el ultimo post para este tema"""
        if not hasattr(self, '__thread_latest_post'):
            try:
                self.__thread_latest_post = Post.objects.filter(thread__pk=self.id).latest('time')
            except Post.DoesNotExist:
                self.__thread_latest_post = self

        return self.__thread_latest_post
    thread_latest_post = property(_get_thread_latest_post)

    class Meta:
        ordering = ["-time"]
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'

    def save(self, force_insert=False, force_update=False):
        if not self.id:
            self.time = datetime.datetime.now()

        f = self.forum
        f.threads = f.thread_set.count()+1
        f.save()
	if self.id:
            pass
        else:
            n = Thread.objects.all().count()
            self.slug = str(n) + '-' + slugify(self.titulo)
	super(Thread, self).save(force_insert, force_update)

    def delete(self):
        super(Thread, self).delete()
        f = self.forum
        f.threads = f.thread_set.count()
        f.posts = Post.objects.filter(thread__forum__pk=f.id).count()
        f.save()

    def __unicode__(self):
        return u'%s' % self.titulo

class Post(models.Model):
    forum = models.ForeignKey(Forum)
    thread = models.ForeignKey(Thread)
    author = models.ForeignKey(User)
    body = models.TextField()
    time = models.DateTimeField(blank=True, null=True)

    def save(self, force_insert=False, force_update=False):
        if not self.id:
            self.time = datetime.datetime.now()
        super(Post, self).save(force_insert, force_update)

        t = self.thread
        t.latest_post_time = t.post_set.latest('time').time
        t.posts = t.post_set.count()
        t.save()

        f = self.thread.forum
        f.threads = f.thread_set.count()
        f.posts = Post.objects.filter(thread__forum__pk=f.id).count()
        f.save()

    def delete(self):
        try:
            latest_post = Post.objects.exclude(pk=self.id).latest('time')
            latest_post_time = latest_post.time
        except Post.DoesNotExist:
            latest_post_time = None

        t = self.thread
        t.posts = t.post_set.exclude(pk=self.id).count()
        t.latest_post_time = latest_post_time
        t.save()

        f = self.thread.forum
        f.posts = Post.objects.filter(thread__forum__pk=f.id).exclude(pk=self.id).count()
        f.save()

        super(Post, self).delete()


    class Meta:
        ordering = ["time"]
        verbose_name = 'Respuesta'
        verbose_name_plural = 'Respuestas'

    def __unicode__(self):
        return u"Respuestas en %s" % self.thread.titulo

biodiversity/forum/forms.py
from django import forms
from models import *

class TopicForm(forms.ModelForm):
    class Meta:
        model = Thread
        exclude = ['forum', 'author', 'posts', 'visto', 'slug', 'time', 'latest_post_time',]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['forum', 'thread', 'author', 'time',]

biodiversity/forum/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.http import *
import datetime
from forum.models import *
from forum.forms import *


def index(request):
    request.session['flag'] = 'foro'
    categorias = Categories.objects.all()
    total_post = Post.objects.all().count()
    total_topics = Thread.objects.all().count()
    total_users = User.objects.all().count()

    return render_to_response('forum/index.html', locals(),
                              context_instance=RequestContext(request))

def forum_list(request, slug):
    flag = 'foro'
    try:
        forum = Forum.objects.get(slug=slug)
    except ObjectDoesNotExist:
        Http404

    total_post = Post.objects.all().count()
    total_topics = Thread.objects.all().count()
    total_users = User.objects.all().count()

    return render_to_response('forum/forum_list.html', locals(),
                               context_instance=RequestContext(request))

def forum_detail(request, slug, t_slug):
    flag = 'foro'
    try:
        thread = Thread.objects.get(slug=t_slug)
        thread.visto = thread.visto+1
        thread.save()

        posts = thread.post_set.all()
    except ObjectDoesNotExist:
        Http404

    return render_to_response('forum/forum_detail.html', locals(),
                               context_instance=RequestContext(request))

@login_required(redirect_field_name='next')
def new_topic(request, slug):
    flag = 'foro'
    try:
        forum = Forum.objects.get(slug=slug)
    except ObjectDoesNotExist:
        Http404

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = Thread()
            topic.forum = forum
            topic.author = request.user
            topic.titulo = form.cleaned_data['titulo']
            topic.body = form.cleaned_data['body']
            topic.save()
            try:
                request.user.get_profile().mas_ranking()
                la = LastActivity()
                la.member = request.user.get_profile()
                la.tipo = 'abrio_foro'
                la.titulo = form.cleaned_data['titulo']
                la.url = 'http://bioversity.simasni.org/foro/'+slug+'/'+slugify(form.cleaned_data['titulo'])+'/'
                la.fecha = datetime.datetime.now()
                la.save()
            except:
                pass
            return HttpResponseRedirect('/foro/'+slug+'/')
    else:
        form = TopicForm()

    return render_to_response('forum/new_topic.html', locals(),
                              context_instance=RequestContext(request))

@login_required(redirect_field_name='next')
def topic_reply(request, slug, t_slug):
    flag = 'foro'
    try:
        forum = Forum.objects.get(slug=slug)
    except ObjectDoesNotExist:
        Http404

    try:
        thread = Thread.objects.get(slug=t_slug)
    except ObjectDoesNotExist:
        Http404

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = Post()
            post.forum = forum
            post.thread = thread
            post.author = request.user
            post.body = form.cleaned_data['body']
            post.save()
            try:
                request.user.get_profile().mas_ranking()
                la = LastActivity()
                la.member = request.user.get_profile()
                la.tipo = 'respondio_foro'
                la.titulo = thread.titulo
                la.url = 'http://bioversity.simasni.org/foro/'+slug+'/'+t_slug+'/'
                la.fecha = datetime.datetime.now()
                la.save()
            except:
                pass
            return HttpResponseRedirect('/foro/'+slug+'/'+t_slug+'/')
    else:
        form = PostForm()

    return render_to_response('forum/reply.html', locals(),
                               context_instance=RequestContext(request))

biodiversity/forum/templates/forum/forum_detail.html
{% extends "base.html" %}

{% block extratitle %}{{thread.titulo|title}}{% endblock %}
{% block extrahead %}

{% endblock %}
{% block contenido %}
<div>    
    <div class="controls">
        <a href="../post/new/" class="new">
            <img src="/files/img/forum/new_post.png" alt="nuevo tema">Nuevo Tema
        </a>&nbsp;&nbsp;
        <a href="./responder/" class="new">
            <img src="/files/img/forum/reply.png" alt="responder">Responder
        </a>
    </div>
    <div class="breadcrumbs">
        <a href="../../">Foro &raquo; </a><a href="../">{{thread.forum|title}} &raquo;</a> {{thread.titulo|title}}
    </div>
    <div class="clean"></div>
    <table cellspacing="1" width="100%">
        <tr>
            <th width="150px" class="azul">&nbsp;Autor&nbsp;</th>
            <th class="azul">&nbsp;Mensaje&nbsp;</th>
        </tr>
        <tr>
            <td class="row1" align="center"><a href=".">
                    <span style="font-size: 14px;">
                        <b>{{thread.author.username}}</b>
                    </span>
                </a></td>
            <td class="row1"><b>Titulo: </b>{{thread.titulo|title}} <div style="float: right;"><b>Posteado: </b>{{thread.time|date:"M j, Y f a"}}</div></td>
        </tr>
        <tr>
            <td class="row1" style="vertical-align: top;">
                <div style="font-size: 10px;">
                    <center><img class="forum-avatar" src="/files/img/forum/user.png" alt="Imagen usuario"></center>
                    <p><b>Joined: </b> {{thread.author.date_joined|date:"M j, Y f a"}}<p>
                        <b>Post: </b>{{thread.author.post_set.count}}<br><br>
                        <b style="color: #069;">{{thread.author.get_full_name}}</b>
                </div>
            </td>
            <td class="row1" style="vertical-align: top;"><div class="postbody">{{thread.body|safe}}</div>
                <br clear= all;>
                <br>
            </td>
        </tr>
    </table>
    <br>    
    {% for post in posts %}
    <table cellspacing="1" width="100%">
        <tr>
            <th width="150px" class="row2" style="padding: 7px 5px;"><a href="."><span style="font-size: 12px;"><b>{{post.author.username}}</b></span></a></th>
            <th class="row2"><div style="float: left;"><b>Re: </b>{{thread.titulo|title}}</div><div style="float: right;"><b>Posteado: </b>{{post.time|date:"M j, Y f a"}}</div></th>
        </tr>
        <tr>
            <td class="row1" style="vertical-align: top;">
                <div style="font-size: 10px;">
                    <center><img class="forum-avatar" src="/files/img/forum/user.png" alt="user no image"></center>
                    <p><b>Joined: </b> {{post.author.date_joined|date:"M j, Y f a"}}<p>
                        <b>Post: </b>{{post.author.post_set.count}}<br><br>
                        <b style="color: #069;">{{post.author.get_full_name}}</b>
                </div>
            </td>
            <td class="row1" style="vertical-align: top;"><div class="postbody">{{post.body|safe}}</div>
                <br clear= all;>
                <br>
            </td>
        </tr>
    </table>
    <br>
    {% endfor %}
    <div style="font-size: 12px;"><center></center></div>
    <div style="float: right;"><a href="../post/new/" class="new"></a><a href="./post/reply/" class="reply"></a></div><br><br>
</div>
{% endblock %}

biodiversity/forum/templates/forum/forum_list.html
{% extends "base.html" %}
{% block extratitle %} {{forum.titulo}}{% endblock %}
{% block extrahead %}

{% endblock %}
{% block contenido %}
<div>        
    <div class="controls">
        <a href="./post/new/" class="new">
            <img src="/files/img/forum/new_post.png" alt="nuevo tema">Nuevo Tema
        </a>
    </div>
    <div class="breadcrumbs">
        <a href="../">Foro &raquo; </a>{{forum.titulo|title}}
    </div>
    <div class="clean"></div>
    <table cellspacing="1" width="100%">
        <tr>
            <th class="azul" colspan="2">&nbsp;Temas&nbsp;</th>
            <th class="azul" width="50">&nbsp;Autor&nbsp;</th>
            <th class="azul" width="50">&nbsp;Respuestas&nbsp;</th>
            <th class="azul" width="50">&nbsp;Vistas&nbsp;</th>
            <th class="azul">&nbsp;Ultimo mensaje&nbsp;</th>
        </tr>
        {% for tema in forum.thread_set.all %}
        <tr>
            <td class="row1" width="50" align="center"><img src="/files/img/forum/topic.png" alt="{{tema.titulo}}" title="{{tema.titulo}}" /></td>
            <td class="row1" width="100%">
                <div style="margin-left: 10px;">
                    <a class="forumlink" href="{{tema.slug}}/">{{tema.titulo}}</a>
                </div>
            </td>
            <td class="row2" align="center">
                <p class="topicdetails">
                    <a href="">{{tema.author}}</a></p></td>
            <td class="row1" align="center"><p class="topicdetails">{{tema.post_set.all.count}}</p></td>
            <td class="row2" align="center"><p class="topicdetails">{{tema.visto}}</p></td>
            <td class="row1 last-post" width="50" align="center">
                <p class="topicdetailsx" style="white-space: nowrap;">
			    {% if tema.latest_post_time %}{{tema.latest_post_time|date:"M j, Y f a"}}{% else %}{{tema.thread_latest_post.time|date:"M j, Y f a"}}{% endif %}
                </p>
                <p class="topicdetailsx" style="white-space: nowrap;">por:
                    <a href="">{{tema.thread_latest_post.author.username}}</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <table cellspacing="1" width="100%" style="margin-top: 20px;">
        <tr>
            <th class="azul" colspan="5" style="text-align: left;">&nbsp;Estad&iacute;sticas&nbsp;</th>
        </tr>
        <tr>
            <td class="row1" width="50" align="center"><img src="/files/img/forum/stats.png" alt="No new posts" title="No new posts" /></td>
            <td class="row1" width="100%" collspan="4">
                <div style="margin-left: 10px;">
                    <p class="forumdesc">Total Post: <span style="font-weight: bold; color: #069;">{{total_post}}</span> | Total de Temas: <span style="font-weight: bold; color: #069;">{{total_topics}}</span> | Total de miembros: <span style="font-weight: bold; color: #069;">{{total_users}}</span></p>
                </div>
                <!--<p class="forumdesc"><strong>Subforum: </strong> <a href="./viewforum.php?f=9&amp;sid=369664c73fb29c30b7ab2d1cceda298f" class="subforum read" title="No new posts">Announcements Discussions</a></p>-->
            </td>
        </tr>
    </table>
</div>
{% endblock %}

biodiversity/forum/templates/forum/index.html
{% extends "base.html" %}
{% block extratitle %}Categorias{% endblock %}
{% block extrahead %}

{% endblock %}
{% block contenido %}<br>
<span class="general_title">Foros Bioversity</span>
<br><br>
<div>
    <table cellspacing="1" width="100%">
        <tr>
            <th class="azul" colspan="2">&nbsp;Foros&nbsp;</th>
            <th class="azul" width="50">&nbsp;Temas&nbsp;</th>
            <th class="azul" width="50">&nbsp;Posts&nbsp;</th>
            <th class="azul">&nbsp;Ultimo post&nbsp;</th>
        </tr>
        {% for categoria in categorias %}
        <tr>
            <td class="forum-cat" colspan="5"><a href="">{{categoria.titulo|title}}</a></td>
        </tr>
        {% for foro in categoria.forum_set.all %}
        <tr>
            <td class="row1" width="50" align="center"><img src="/files/img/forum/post.png" alt="{{foro.titulo}}" title="{{foro.titulo}}" /></td>
            <td class="row1" width="100%">
                <div style="margin-left: 10px;">
                    <a class="forumlink" href="{{foro.slug}}/">{{foro.titulo}}</a>
                    <p class="forumdesc">{{foro.descripcion|safe}}</p>
                </div>
                <!--<p class="forumdesc"><strong>Subforum: </strong> <a href="./viewforum.php?f=9&amp;sid=369664c73fb29c30b7ab2d1cceda298f" class="subforum read" title="No new posts">Announcements Discussions</a></p>-->
            </td>
            <td class="row2" align="center"><p class="topicdetails">{{foro.thread_set.all.count}}</p></td>
            <td class="row2" align="center"><p class="topicdetails">{{foro.post_set.all.count}}</p></td>
            <td class="row1 last-post" >
                <p class="topicdetailsx" style="white-space: nowrap;">Ultimo mensaje por: 
                    <a href="">{{foro.forum_latest_post.author}}</a>
                </p>
                <p class="topicdetailsx">en
                    <a href="{{foro.forum_latest_post.forum.slug}}/{{foro.forum_latest_post.thread.slug}}">
                        {{foro.forum_latest_post.thread.titulo}}
                    </a>
                </p>
                <p class="topicdetailsx" style="white-space: nowrap;">el {{foro.forum_latest_post.time|date:"M j, Y f a"}}</p>
            </td>
        </tr>
        {% endfor %}
        {% endfor %}
    </table>
    <table cellspacing="1" width="100%" style="margin-top: 20px;">
        <tr>
            <th class="azul" colspan="5" style="text-align: left;">&nbsp;Estad&iacute;sticas&nbsp;</th>
        </tr>
        <tr>
            <td class="row1" width="50" align="center"><img src="/files/img/forum/stats.png" alt="No new posts" title="No new posts" /></td>
            <td class="row1" width="100%" collspan="4">
                <div style="margin-left: 10px;">
                    <p class="forumdesc">Total Post: <span style="font-weight: bold; color: #069;">{{total_post}}</span> | Total de Temas: <span style="font-weight: bold; color: #069;">{{total_topics}}</span> | Total de miembros: <span style="font-weight: bold; color: #069;">{{total_users}}</span></p>
                </div>
                <!--<p class="forumdesc"><strong>Subforum: </strong> <a href="./viewforum.php?f=9&amp;sid=369664c73fb29c30b7ab2d1cceda298f" class="subforum read" title="No new posts">Announcements Discussions</a></p>-->
            </td>
        </tr>
    </table>
</div>
{% endblock %}

biodiversity/forum/templates/forum/new_topic.html
{% extends "base.html" %}
{% block extratitle %} Nuevo Tema{% endblock %}
{% block extra_header %}
<script type="text/javascript" src="/files/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        mode: "textareas",
        theme: "advanced",
        theme_advanced_buttons1: "bold,italic,underline, strikethrough, separator,justifyleft, justifycenter,justifyright,  justifyfull, separator",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        theme_advanced_buttons4: "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left"
    }); 
</script>

<style type="text/css">
    label{
        font-size: 12px;
    }

    input#id_titulo{
        border: 1px solid #BFBFBF;
        padding: 2px;
        width: 250px;
    }

    textarea{
        width: 100%;
        height: 200px;
    }
    .submit{
        margin-left: 15px;
    }
</style>
{% endblock %}
{% block contenido %}
<div class="breadcrumbs">
    <a href="../../">Foro &raquo; </a> {{forum.titulo|title}}
</div>
<div class="clean"></div>
<div>
    <br>
    <div class="respuesta">Nuevo tema en: <span class="to">{{forum.titulo|title}}</span></div><br>
    <form action="." method="POST" class="topic-form" id="topic-form">{% csrf_token %}
        <table cellspacing="1" width="100%" style="background: #f2f3e6; padding: 10px;">
            {{form.as_table}}
        </table><br>
        <input type="submit" class="submit" value="Crear"> <button onclick="window.location.href='/foro/{{forum.slug}}'; return false;">Cancelar</button>
    </form>
</div>
{% endblock %}

biodiversity/forum/templates/forum/reply.html
{% extends "base.html" %}
{% block extratitle %} Responder{% endblock %}
{% block extra_header %}
<script type="text/javascript" src="/files/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">    
    tinyMCE.init({
        mode : "textareas",
        theme : "advanced",
        theme_advanced_buttons1 : "bold,italic,underline, strikethrough, separator,justifyleft, justifycenter,justifyright,  justifyfull, separator",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        theme_advanced_buttons4: "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left"
    });    
</script>
<style type="text/css">
    label{
        font-size: 12px;
    }

    input#id_titulo{
        border: 1px solid #BFBFBF;
        padding: 2px;
        width: 250px;
    }

    textarea{
        width: 99.5%;
        height: 150px;        
    }

    .submit{
        margin-left: 15px;
    }
</style>
{% endblock %}
{% block contenido %}
<div class="breadcrumbs">
    <a href="../../../">Foro &raquo; </a><a href="../../">{{thread.forum|title}} &raquo;</a> {{thread.titulo|title}}
</div>
<div class="clean"></div>
<div>
    <br>
    <div class="respuesta">Respuesta a: <span class="to">{{thread.titulo|title}}</span></div><br>
    <form action="." method="POST" class="topic-form" id="topic-form">{% csrf_token %}
        <div>{{form.body}}</div>
        <br>
        <input type="submit" class="submit" value="Responder"> <button onclick="javascript:history.back(1); return false;">Cancelar</button>
    </form>
</div>
<div>
    <br>
    <table cellspacing="1" width="100%">
        <tr>
            <th width="150px" class="azul">&nbsp;Autor&nbsp;</th>
            <th class="azul">&nbsp;Mensaje original&nbsp;</th>
        </tr>
        <tr>
            <td class="row1" align="center"><a href="."><span style="font-size: 14px;"><b>{{thread.author.username}}</b></span></a></td>
            <td class="row1"><b>Titulo: </b>{{thread.titulo|title}} <div style="float: right;"><b>Posteado: </b>{{thread.time|date:"M j, Y f a"}}</div></td>
        </tr>
        <tr>
            <td class="row1">
                <div style="font-size: 10px;">
                    <center><img class="forum-avatar" src="/files/img/forum/user.png" alt=""></center>
                    <p><b>Joined: </b> {{thread.author.date_joined|date:"M j, Y f a"}}<p>
                        <b>Post: </b>{{thread.author.post_set.count}}<br><br>
                        <b style="color: #069;">{{thread.author.get_full_name}}</b>
                </div>
            </td>
            <td class="row1" style="vertical-align: top;"><div class="postbody">{{thread.body|safe}}</div>
                <br clear= all;>
                <br>
            </td>
        </tr>
    </table>
    <br>
    {% for post in thread.post_set.all %}
    <table cellspacing="1" width="100%">
        <tr>
            <th width="150px" class="row2" style="padding: 7px 5px;"><a href="."><span style="font-size: 12px;"><b>{{post.author.username}}</b></span></a></th>
            <th class="row2"><div style="float: left;"><b>Re: </b>{{thread.titulo|title}}</div><div style="float: right;"><b>Posteado: </b>{{post.time|date:"M j, Y f a"}}</div></th>
        </tr>
        <tr>
            <td class="row1" style="vertical-align: top;">
                <div style="font-size: 10px;">
                    <center><img class="forum-avatar" src="/files/img/forum/user.png" alt=""></center>
                    <p><b>Joined: </b> {{post.author.date_joined|date:"M j, Y f a"}}<p>
                        <b>Post: </b>{{post.author.post_set.count}}<br><br>
                        <b style="color: #069;">{{post.author.get_full_name}}</b>
                </div>
            </td>
            <td class="row1" style="vertical-align: top;"><div class="postbody">{{post.body|safe}}</div>
                <br clear= all;>
                <br>
            </td>
        </tr>
    </table>
    <br>
    {% endfor %}
    <br>
</div>
{% endblock %}